const { v4: uuidv4 } = require('uuid');
/**
 * Express Middleware to,
 * Sets response header with autogenerated `reqTrackingId`
 * @param {*} req 
 * @param {*} res 
 * @param {*} next 
 */
module.exports = function(req, res, next) {
  res.setHeader('reqTrackingId', uuidv4());
  next();
};