name: Publish npm package
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --omit=dev
      - run: npm publish --provenance --access public --tag ${{ github.ref }}
        env:
          npm_config__auth: //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
